### ISSUE TITLE
Got "fatal: Not a git repository (or any of the parent directories): .git" whem compiling libinvm-i18n

### ISSUE THREAD

**Issue by yide1728** [01org/libinvm-i18n#3]
#wget https://github.com/01org/libinvm-i18n/archive/v1.0.0.1016.tar.gz#/libinvm-i18n-1.0.0.1016.tar.gz
#tar xvf v1.0.0.1018.tar.gz
#cd libinvm-i18n-1.0.0.1018/
#make 
**fatal: Not a git repository (or any of the parent directories): .git**
make -C src all SKIP_UNITTESTS=1
**fatal: Not a git repository (or any of the parent directories): .git**
make[1]: Entering directory `/root/tmp/libinvm-i18n-1.0.0.1018/src'
mkdir -p ../output/build/linux/debug
mkdir -p ../output/obj/linux/debug/Intel_i18n
gcc -Wall -Werror -Wfatal-errors -fstack-protector-all -D_FORTIFY_SOURCE=2 -D_XOPEN_SOURCE=500  -fPIC -m64 -O -ggdb -std=c99 -MMD -D__VERSION_MAJOR__=99 -D__VERSION_MINOR__=99 -D__VERSION_HOTFIX__=99 -D__VERSION_BUILDNUM__=9999 -D__VERSION_NUMBER__=99.99.99.9999   -D__LINUX__  -D_GNU_SOURCE -I../src -c textdomain.c -o ../output/obj/linux/debug/Intel_i18n/textdomain.o
gcc -Wall -Werror -Wfatal-errors -fstack-protector-all -D_FORTIFY_SOURCE=2 -D_XOPEN_SOURCE=500  -fPIC -m64 -O -ggdb -std=c99 -MMD -D__VERSION_MAJOR__=99 -D__VERSION_MINOR__=99 -D__VERSION_HOTFIX__=99 -D__VERSION_BUILDNUM__=9999 -D__VERSION_NUMBER__=99.99.99.9999   -D__LINUX__  -D_GNU_SOURCE -I../src -c gettext.c -o ../output/obj/linux/debug/Intel_i18n/gettext.o
gcc -Wall -Werror -Wfatal-errors -fstack-protector-all -D_FORTIFY_SOURCE=2 -D_XOPEN_SOURCE=500  -fPIC -m64 -O -ggdb -std=c99 -MMD -D__VERSION_MAJOR__=99 -D__VERSION_MINOR__=99 -D__VERSION_HOTFIX__=99 -D__VERSION_BUILDNUM__=9999 -D__VERSION_NUMBER__=99.99.99.9999   -D__LINUX__  -D_GNU_SOURCE -I../src -c posix_system.c -o ../output/obj/linux/debug/Intel_i18n/posix_system.o
gcc -Wall -Werror -Wfatal-errors -fstack-protector-all -D_FORTIFY_SOURCE=2 -D_XOPEN_SOURCE=500  -fPIC -m64 -O -ggdb -std=c99 -MMD -D__VERSION_MAJOR__=99 -D__VERSION_MINOR__=99 -D__VERSION_HOTFIX__=99 -D__VERSION_BUILDNUM__=9999 -D__VERSION_NUMBER__=99.99.99.9999   -D__LINUX__  -D_GNU_SOURCE -I../src -c gettext_dummy.c -o ../output/obj/linux/debug/Intel_i18n/gettext_dummy.o
gcc -Wall -Werror -Wfatal-errors -fstack-protector-all -D_FORTIFY_SOURCE=2 -D_XOPEN_SOURCE=500  -fPIC -m64 -O -ggdb -std=c99 -MMD -D__VERSION_MAJOR__=99 -D__VERSION_MINOR__=99 -D__VERSION_HOTFIX__=99 -D__VERSION_BUILDNUM__=9999 -D__VERSION_NUMBER__=99.99.99.9999   -D__LINUX__  -D_GNU_SOURCE -I../src -c safe_str.c -o ../output/obj/linux/debug/Intel_i18n/safe_str.o
gcc -Wall -Werror -Wfatal-errors -fstack-protector-all -D_FORTIFY_SOURCE=2 -D_XOPEN_SOURCE=500  -fPIC -m64 -O -ggdb  -MMD -D__VERSION_MAJOR__=99 -D__VERSION_MINOR__=99 -D__VERSION_HOTFIX__=99 -D__VERSION_BUILDNUM__=9999 -D__VERSION_NUMBER__=99.99.99.9999   -D__LINUX__   -shared ../output/obj/linux/debug/Intel_i18n/textdomain.o ../output/obj/linux/debug/Intel_i18n/gettext.o ../output/obj/linux/debug/Intel_i18n/posix_system.o ../output/obj/linux/debug/Intel_i18n/gettext_dummy.o ../output/obj/linux/debug/Intel_i18n/safe_str.o  -Wl,-soname,libinvm-i18n.so.99 -o ../output/build/linux/debug/libinvm-i18n.so.99.99.0
cd ../output/build/linux/debug; rm -f libinvm-i18n.so.99; ln -s libinvm-i18n.so.99.99.0 libinvm-i18n.so.99
cd ../output/build/linux/debug; rm -f libinvm-i18n.so; ln -s libinvm-i18n.so.99.99.0 libinvm-i18n.so
mkdir -p ../output/build/linux/debug/include/libinvm-i18n
cp -rav libIntel_i18n.h ../output/build/linux/debug/include/libinvm-i18n
‘libIntel_i18n.h’ -> ‘../output/build/linux/debug/include/libinvm-i18n/libIntel_i18n.h’
make[1]: Leaving directory `/root/tmp/libinvm-i18n-1.0.0.1018/src'

**Comment by nkothapa** [comment]
Fixed it in the latest release, Thanks for the report!
